export const PHONE_COUNTRY_CODES: { code: string; name: string }[] = [
  { code: '+52', name: 'Mexico' },
  // { code: '+1', name: 'United States' },
  // { code: '+1', name: 'Canada' },
  // { code: '+34', name: 'Spain' },
  // { code: '+44', name: 'United Kingdom' },
  // { code: '+55', name: 'Brazil' },
  // { code: '+54', name: 'Argentina' },
  // { code: '+56', name: 'Chile' },
  // { code: '+57', name: 'Colombia' },
  // { code: '+58', name: 'Venezuela' },
  // { code: '+51', name: 'Peru' },
  // { code: '+598', name: 'Uruguay' },
  // { code: '+591', name: 'Bolivia' },
  // { code: '+507', name: 'Panama' },
  // { code: '+506', name: 'Costa Rica' },
  // { code: '+502', name: 'Guatemala' },
  // { code: '+504', name: 'Honduras' },
  // { code: '+503', name: 'El Salvador' },
  // { code: '+595', name: 'Paraguay' },
  // { code: '+39', name: 'Italy' },
  // { code: '+33', name: 'France' },
  // { code: '+49', name: 'Germany' },
  // { code: '+31', name: 'Netherlands' },
  // { code: '+32', name: 'Belgium' },
  // { code: '+353', name: 'Ireland' },
  // { code: '+351', name: 'Portugal' },
  // { code: '+47', name: 'Norway' },
  // { code: '+46', name: 'Sweden' },
  // { code: '+45', name: 'Denmark' },
  // { code: '+358', name: 'Finland' },
  // { code: '+420', name: 'Czech Republic' },
  // { code: '+36', name: 'Hungary' },
  // { code: '+48', name: 'Poland' },
  // { code: '+86', name: 'China' },
  // { code: '+81', name: 'Japan' },
  // { code: '+82', name: 'South Korea' },
  // { code: '+60', name: 'Malaysia' },
  // { code: '+65', name: 'Singapore' },
  // { code: '+66', name: 'Thailand' },
  // { code: '+62', name: 'Indonesia' },
  // { code: '+63', name: 'Philippines' },
  // { code: '+91', name: 'India' },
  // { code: '+92', name: 'Pakistan' },
  // { code: '+971', name: 'United Arab Emirates' },
  // { code: '+966', name: 'Saudi Arabia' },
  // { code: '+27', name: 'South Africa' },
  // { code: '+20', name: 'Egypt' },
  // { code: '+380', name: 'Ukraine' },
  // { code: '', name: 'Other' },
];

export default PHONE_COUNTRY_CODES;
