import { PublicHeader } from "@/components/layouts/PublicHeader";
import { PublicFooter } from "@/components/layouts/PublicFooter";

const TerminosCondiciones = () => {
  return (
    <div className="min-h-screen bg-background">
      <PublicHeader />

      <main className="pt-20 sm:pt-24 pb-16">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 sm:py-12">
          <h1 className="text-xl sm:text-2xl font-bold text-primary mb-6">Términos y Condiciones de Uso</h1>

          <div className="text-sm text-foreground/90 space-y-4">
            <h2 className="text-lg sm:text-xl font-bold text-primary mt-6 mb-4">GENERALES</h2>

            <p className="text-justify">
              LOS PRESENTES TÉRMINOS Y CONDICIONES DE USO, EN LO SUCESIVO LOS "TÉRMINOS Y CONDICIONES", REGULAN EL ACCESO Y LA UTILIZACIÓN DE LA PLATAFORMA, ALOJADA BAJO EL NOMBRE DE DOMINIO WWW.INCRESCENDOFINTECH.COM, ASÍ COMO LA APLICACIÓN MÓVIL, (EN LO SUCESIVO "WALLET"), ASÍ COMO LOS CONTENIDOS Y SERVICIOS QUE INCRESCENDO FINTECH MX, S.A.P.I. DE C.V. (EN LO SUCESIVO "INCRESCENDO FINTECH") PONE A DISPOSICIÓN DEL "USUARIO Y/O CLIENTE", AL CONTRATAR SU MEMBRESÍA.
            </p>

            <p className="text-justify">
              ASIMISMO, LOS PRESENTES "TÉRMINOS Y CONDICIONES" ESTABLECEN JUNTO CON EL AVISO DE PRIVACIDAD, RELATIVO A LA GESTIÓN DE DATOS DE CARÁCTER PERSONAL DEL "USUARIO Y/O CLIENTE", LOS TÉRMINOS Y CONDICIONES POR LOS QUE SE RIGE LA "WALLET", EN CUMPLIMIENTO DEL ARTÍCULO 80 Y 89 AL 95 DEL CÓDIGO DE COMERCIO Y EN TÉRMINOS DE LO DISPUESTO POR EL ARTÍCULO 1803 DEL CÓDIGO CIVIL FEDERAL; ASÍ COMO LA LEY FEDERAL PARA LA PREVENCIÓN E IDENTIFICACIÓN DE OPERACIONES CON RECURSOS DE PROCEDENCIA ILÍCITA, SU REGLAMENTO Y DISPOSICIONES GENERALES EMITIDAS POR LA SECRETARIA DE HACIENDA Y CRÉDITO PÚBLICO; POR LO QUE SE EXPONEN LOS SIGUIENTES:
            </p>

            <h2 className="text-lg sm:text-xl font-bold text-primary mt-8 mb-4">LINEAMIENTOS</h2>

            <h3 className="text-base sm:text-lg font-semibold text-foreground mt-6 mb-3">(A) LICENCIA Y RESTRICCIONES DE USO DE LA "WALLET"</h3>

            <p className="text-justify">
              AL LLEVAR A CABO EL PROCEDIMIENTO DE REGISTRO Y CREACIÓN DE NÚMERO DE CLIENTE Y/O CUENTA A TRAVÉS DE LA "WALLET", EL "USUARIO Y/O CLIENTE" RECONOCE, ACEPTA Y OTORGA EXPRESAMENTE SU CONSENTIMIENTO CON LOS "TÉRMINOS Y CONDICIONES", EN LOS QUE "INCRESCENDO FINTECH" LE CONCEDE AL "USUARIO Y/O CLIENTE" UNA MEMBRESÍA INTRANSFERIBLE DE USO TEMPORAL DE DICHA "WALLET", NO EXCLUSIVA Y REVOCABLE, SIN QUE ESTO IMPLIQUE QUE EL "USUARIO Y/O CLIENTE" ADQUIERA NINGÚN DERECHO DE PROPIEDAD INTELECTUAL POR EL SIMPLE USO DE LOS SERVICIOS Y CONTENIDOS DE LA "WALLET"; POR LO QUE EL ÚNICO CANAL DE ACCESO POR EL CUAL EL "USUARIO Y/O CLIENTE" PODRÁ EFECTUAR LAS OPERACIONES, ACTIVIDADES Y SERVICIOS DERIVADOS DE LA CONTRATACIÓN DE SU MEMBRESÍA, TALES COMO LA OPERACIÓN DE SU CUENTA DE PAGOS ELECTRÓNICOS, ENTRE OTROS, SERÁ A TRAVÉS DE LA "WALLET". EN NINGÚN MOMENTO, EL USO DE LA "WALLET" SERÁ CONSIDERADO COMO UNA AUTORIZACIÓN O LICENCIA PARA UTILIZAR LOS SERVICIOS Y CONTENIDOS CON FINES DISTINTOS A LOS QUE SE CONTEMPLAN EN LOS "TÉRMINOS Y CONDICIONES". EN VIRTUD DE LO ANTERIOR, QUEDA PROHIBIDO UTILIZAR, DIVULGAR, REPRODUCIR, MODIFICAR, ALTERAR, SUPRIMIR O EXPLOTAR, YA SEA EN FORMA TOTAL O PARCIAL LAS MARCAS, LOGOTIPOS, DISEÑOS, AVISOS, ANUNCIOS Y DEMÁS CONCEPTOS ANÁLOGOS CONTENIDOS EN LA "WALLET".
            </p>

            <p className="text-justify">
              "INCRESCENDO FINTECH", TENDRÁ DERECHO A NEGAR, RESTRINGIR O CONDICIONAR EL ACCESO A LA "WALLET", TOTAL O PARCIALMENTE AL "USUARIO Y/O CLIENTE", POR CUALQUIER INCUMPLIMIENTO A LO ESTABLECIDO EN LOS "TÉRMINOS Y CONDICIONES" O BIEN, POR SITUACIONES QUE "INCRESCENDO FINTECH" CONSIDERE RIESGOSAS PARA EL DEBIDO FUNCIONAMIENTO DE LA "WALLET" O A SUS DERECHOS DE PROPIEDAD INTELECTUAL, SIN PREVIO AVISO.
            </p>

            <p className="text-justify">
              EN CASO DE QUE "INCRESCENDO FINTECH", DECIDA SUSPENDER EL ACCESO A LA "WALLET" AL "USUARIO Y/O CLIENTE", DE MANERA TOTAL Y PERMANENTEMENTE, SE PROCEDERÁ AL CIERRE DE LOS SERVICIOS, NOTIFICANDO DICHA DETERMINACIÓN AL "USUARIO Y/O CLIENTE" VÍA CORREO ELECTRÓNICO.
            </p>

            <p className="text-justify">
              EL "USUARIO Y/O CLIENTE" RECONOCE Y ACEPTA QUE "INCRESCENDO FINTECH", PODRÁ EN CUALQUIER MOMENTO Y SIN NECESIDAD DE DARLE AVISO, MODIFICAR LOS "TÉRMINOS Y CONDICIONES", ASI COMO, REALIZAR ACTUALIZACIONES, CORRECCIONES, ADICIONES, MEJORAS O MODIFICACIONES AL CONTENIDO, PRESENTACIÓN E INFORMACIÓN DE LA "WALLET", CON EL FIN DE QUE ESTA FUNCIONE EFICIENTEMENTE Y MEJORE LA EXPERIENCIA DEL "USUARIO Y/O CLIENTE" EN SU USO.
            </p>

            <p className="text-justify">
              EN CASO DE QUE "USUARIO Y/O CLIENTE" NO DESEE UTILIZAR LA "WALLET", "INCRESCENDO FINTECH", NO PODRÁ CONTINUAR CON LA PRESTACIÓN DE SUS SERVICIOS Y SE PROCEDERÁ CON LA CANCELACIÓN DE SU MEMBRESÍA, Y EL NÚMERO DE CLIENTE Y/O CUENTA LIGADA A LA MISMA.
            </p>

            <h3 className="text-base sm:text-lg font-semibold text-foreground mt-6 mb-3">(B) ACTIVIDADES QUE EL "USUARIO Y/O CLIENTE" PODRÁ REALIZAR EN LA "WALLET"</h3>

            <p className="text-justify">
              EL "USUARIO Y/O CLIENTE" EN ESTE ACTO OTORGA EXPRESAMENTE SU CONSENTIMIENTO PARA ACCEDER Y USAR LA "WALLET" PARA REALIZAR LAS OPERACIONES Y ACTIVIDADES, QUE DE MANERA ENUNCIATIVA MAS NO LIMITATIVA SE ENLISTAN A CONTINUACIÓN:
            </p>

            <ol className="list-decimal pl-6 space-y-2 my-4">
              <li className="text-justify">CAPTURA DE INFORMACIÓN Y DOCUMENTACIÓN PARA LA IDENTIFICACIÓN DEL "USUARIO Y/O CLIENTE" REQUERIDA POR "INCRESCENDO FINTECH".</li>
              <li className="text-justify">SOLICITAR LÍNEA DE CRÉDITO Y USO DE LOS BENEFICIOS POR LOS SERVICIOS DE LA MEMBRESÍA VÍA LA "WALLET".</li>
              <li className="text-justify">INSTRUIR TRANSFERENCIAS DE PAGO ELECTRÓNICO, EN MONEDA NACIONAL.</li>
              <li className="text-justify">OBTENER LOS COMPROBANTES DE OPERACIÓN DE LOS ABONOS Y CARGOS QUE SE REALICEN EN LA CUENTA EN LOS ÚLTIMOS 30 DÍAS.</li>
              <li className="text-justify">CONSULTAR EL REGISTRO ACTUALIZADO Y EN TIEMPO REAL DE LOS SALDOS Y MOVIMIENTOS.</li>
              <li className="text-justify">CONSULTAR SUS ESTADOS DE CUENTA, ASÍ COMO SOLICITAR AQUELLOS CON UNA ANTIGÜEDAD MAYOR A 3 MESES DISPONIBLES POR LA "WALLET".</li>
              <li className="text-justify">CONSULTAR EL NIVEL DE CUENTA Y NÚMERO DE CUENTA CLABE ASIGNADO A LA CUENTA DEL "USUARIO Y/O CLIENTE".</li>
              <li className="text-justify">DESIGNAR A LOS BENEFICIARIOS.</li>
              <li className="text-justify">MODIFICAR LA CONTRASEÑA DE ACCESO A LA "WALLET".</li>
              <li className="text-justify">RECIBIR LOS AVISOS Y NOTIFICACIONES A QUE SE REFIEREN LOS PRESENTES "TÉRMINOS Y CONDICIONES", SIN PERJUICIO DE LOS DEMÁS MEDIOS POR LOS QUE PUEDAN REALIZARSE.</li>
              <li className="text-justify">PAGO DE SERVICIOS CON CARGO A SU LÍNEA DE CRÉDITO.</li>
              <li className="text-justify">PRESENTAR AVISOS DE RECLAMACIONES POR CARGOS NO RECONOCIDOS; DE ROBO O EXTRAVÍO DE TARJETA O MEDIOS DE AUTENTICACIÓN, U OTRO TIPO DE ACLARACIONES O SOLICITUDES.</li>
              <li className="text-justify">CUALESQUIERA OPERACIÓN Y/O SERVICIO QUE "INCRESCENDO FINTECH", LLEGARE A AUTORIZAR EN EL FUTURO.</li>
            </ol>

            <p className="text-justify">
              PARA EL INGRESO A LA APLICACIÓN SE UTILIZARÁ EL NOMBRE DE USUARIO Y/O NÚMERO DE CLIENTE PREVIAMENTE REGISTRADOS Y LA CONTRASEÑA QUE EL "USUARIO Y/O CLIENTE" HAYA DEFINIDO EN LA "WALLET".
            </p>

            <p className="text-justify">
              UNA VEZ INICIADA LA SESIÓN, EN CASO DE QUE EL "USUARIO Y/O CLIENTE" NO REALICE NINGÚN MOVIMIENTO DENTRO DE LA "WALLET", POR MÁS DE UN MINUTO CINCUENTA Y OCHO SEGUNDOS, LA SESIÓN SE DARÁ POR TERMINADA DE MANERA INMEDIATA. "INCRESCENDO FINTECH", PODRÁ SUSPENDER LA SESIÓN CUANDO SE PRESENTEN INDICIOS QUE LA PERSONA EN SESIÓN NO ES EL "USUARIO Y/O CLIENTE".
            </p>

            <h3 className="text-base sm:text-lg font-semibold text-foreground mt-6 mb-3">(C) HORARIOS DE DISPONIBILIDAD DE LA "WALLET"</h3>

            <p className="text-justify">
              ESTARÁ DISPONIBLE PARA OPERAR LAS 24 HORAS DEL DÍA, LOS 365 DÍAS DEL AÑO. LO ANTERIOR, ES INDEPENDIENTE A LOS HORARIOS EN QUE SE VEAN REFLEJADAS LAS OPERACIONES CONFORME A LA NORMATIVA APLICABLE AL SISTEMA DE PAGOS ELECTRÓNICOS INTERBANCARIOS (SPEI) EMITIDA POR EL BANCO DE MÉXICO.
            </p>

            <h3 className="text-base sm:text-lg font-semibold text-foreground mt-6 mb-3">(D) REGISTRO EN LA "WALLET" CONTRASEÑAS Y OTROS FACTORES DE AUTENTICACIÓN</h3>

            <p className="text-justify">
              PARA REALIZAR EL ALTA, EL "USUARIO Y/O CLIENTE" INVARIABLEMENTE DEBERÁ CONTAR CON TELÉFONO MÓVIL ACTIVO, ADEMÁS QUE SE LE SOLICITARÁ INFORMACIÓN Y DOCUMENTACIÓN PARA SU DEBIDA IDENTIFICACIÓN, LA CUAL SERÁ VALIDADA POR EL EQUIPO DE "INCRESCENDO FINTECH". POSTERIORMENTE, EL "USUARIO Y/O CLIENTE" DEBERÁ TAMBIÉN DE FIRMAR DE CONFORMIDAD LOS PRESENTES "TÉRMINOS Y CONDICIONES" PARA EL USO DEL SERVICIO, MEDIANTE UNA CONTRASEÑA DE UN SOLO USO (OTP, POR SUS SIGLAS EN INGLÉS) QUE SERÁ ENVIADA VÍA SMS AL NÚMERO DEL TELÉFONO MÓVIL PROPORCIONADO POR EL "USUARIO Y/O CLIENTE". UNA VEZ REALIZADOS LOS PASOS ANTERIORES, EL "USUARIO Y/O CLIENTE" DEBERÁ INGRESAR SU USUARIO Y CONTRASEÑA PARA PODER INGRESAR A SU SESIÓN EN LA "WALLET". "INCRESCENDO FINTECH", SOLICITARÁ AL "USUARIO Y/O CLIENTE" UN SEGUNDO FACTOR DE AUTENTICACIÓN ADICIONAL Y DIFERENTE AL UTILIZADO PARA INICIAR SESIÓN EN LA "WALLET", QUE SERÁ UNA CONTRASEÑA ENVIADA A LA CUENTA DE CORREO ELECTRÓNICO REGISTRADA POR EL "USUARIO Y/O CLIENTE" Y EL CUAL DEBERÁ INGRESARSE EN EL CAMPO ASIGNADO PARA ELLO, EN CADA OCASIÓN QUE SE PRETENDA REALIZAR UNA DE LAS OPERACIONES SIGUIENTES:
            </p>

            <ol className="list-decimal pl-6 space-y-2 my-4">
              <li className="text-justify">INSTRUCCIONES DE TRANSFERENCIAS DE PAGO ELECTRÓNICO.</li>
              <li className="text-justify">CAMBIO Y DESBLOQUEO DE CONTRASEÑA.</li>
              <li className="text-justify">BLOQUEO Y DESBLOQUEO DE TARJETA VIRTUAL Y FÍSICA.</li>
              <li className="text-justify">ALTA Y MODIFICACIÓN DE LOS MEDIOS DE NOTIFICACIÓN AL "USUARIO Y/O CLIENTE".</li>
              <li className="text-justify">CONSULTAS DE ESTADOS DE CUENTA.</li>
              <li className="text-justify">ACTUALIZACIÓN DE DATOS DEL "USUARIO Y/O CLIENTE".</li>
              <li className="text-justify">SOLICITUD DE CIERRE DE CUENTA Y/O SERVICIOS.</li>
              <li className="text-justify">SOLICITUD DE CARGOS RECURRENTES.</li>
            </ol>

            <p className="text-justify">
              PARA EFECTOS DEL SERVICIO DE CARGOS RECURRENTES EL "USUARIO Y/O CLIENTE", A TRAVÉS DEL PROCEDIMIENTO DE SOLICITUD Y AUTENTICACIÓN EN LA "WALLET", INSTRUYE Y AUTORIZA QUE SE REALICEN CARGOS PERIÓDICOS EN SU CUENTA, QUE SE MANTENDRÁN DE MANERA INDEFINIDA, HASTA QUE SOLICITE EL CESE DE DICHOS CARGOS.
            </p>

            <p className="text-justify">
              EL SEGUNDO FACTOR DE AUTENTICACIÓN, UNA VEZ INICIADA LA SESIÓN CON EL MÉTODO TRADICIONAL, SERÁ UN SMS ENVIADO AL TELÉFONO REGISTRADO DEL "USUARIO Y/O CLIENTE", DADO QUE CADA "USUARIO Y/O CLIENTE" DEBE TENER UN TELÉFONO CELULAR RELACIONADO.
            </p>

            <h3 className="text-base sm:text-lg font-semibold text-foreground mt-6 mb-3">(E) RESPONSABILIDAD DEL "USUARIO Y/O CLIENTE" RESPECTO DE LOS FACTORES DE AUTENTICACIÓN</h3>

            <p className="text-justify">
              EL "USUARIO Y/O CLIENTE" RECONOCE Y ACEPTA QUE EL USO DE LOS FACTORES DE AUTENTICACIÓN ES LA FORMA EN QUE "INCRESCENDO FINTECH" IDENTIFICARÁ DE MANERA ÚNICA E INEQUÍVOCA AL "USUARIO Y/O CLIENTE", POR LO QUE CUALQUIER ACCESO A LA "WALLET", U OPERACIÓN INSTRUIDA A TRAVÉS DE LOS REFERIDOS FACTORES DE AUTENTICACIÓN SE CONSIDERARÁ REALIZADA POR EL "USUARIO Y/O CLIENTE", TENIENDO ESTOS LOS MISMOS EFECTOS QUE LAS LEYES OTORGAN A LOS DOCUMENTOS SUSCRITOS CON FIRMA AUTÓGRAFA Y, EN CONSECUENCIA, TENDRÁN EL MISMO VALOR PROBATORIO. POR LO ANTERIOR, EL "USUARIO Y/O CLIENTE" ES EL ÚNICO RESPONSABLE DEL RESGUARDO Y EL DEBIDO USO DE SU CONTRASEÑA Y DEMÁS FACTORES DE AUTENTICACIÓN.
            </p>

            <h3 className="text-base sm:text-lg font-semibold text-foreground mt-6 mb-3">(F) USO ROBO, EXTRAVÍO U OLVIDO DE LAS CONTRASEÑAS</h3>

            <p className="text-justify">
              EN CASO DE ROBO, EXTRAVÍO U OLVIDO DE CONTRASEÑAS, EL "USUARIO Y/O CLIENTE" DEBERÁ SOLICITAR EL CAMBIO DE CONTRASEÑA A TRAVÉS DE LA "WALLET", PARA LO CUAL EL "USUARIO Y/O CLIENTE" DEBERÁ INGRESAR, Y EN LA SECCIÓN DE "CAMBIO DE CONTRASEÑA" SE LE PEDIRÁ QUE INGRESE LA CONTRASEÑA ACTUAL, Y POSTERIORMENTE ESTABLEZCA NUEVAMENTE UNA CONTRASEÑA, ASÍ COMO SU CONFIRMACIÓN.
            </p>

            <h3 className="text-base sm:text-lg font-semibold text-foreground mt-6 mb-3">(G) LÍMITES DE RESPONSABILIDAD</h3>

            <p className="text-justify">
              "INCRESCENDO FINTECH", NO GARANTIZA QUE LA "WALLET", FUNCIONARÁ LIBRE DE ERRORES; SIN EMBARGO, SIEMPRE REALIZARÁ SUS MEJORES ESFUERZOS PARA MANTENER LOS NIVELES DE SERVICIO ADECUADOS DE OPERACIÓN.
            </p>

            <p className="text-justify">
              "INCRESCENDO FINTECH", TAMPOCO SE HACE RESPONSABLE DE QUE LA "WALLET", Y LOS CANALES ELECTRÓNICOS DE COMUNICACIÓN CON EL "USUARIO Y/O CLIENTE" ESTÉN LIBRES DE VIRUS INFORMÁTICOS U OTROS MECANISMOS LESIVOS, POR LO QUE NO RESPONDERÁ AL "USUARIO Y/O CLIENTE" POR LOS GASTOS DE SERVICIOS TÉCNICOS A SUS EQUIPOS O LA REPOSICIÓN DE ESTOS, NI POR EL BLOQUEO O BORRADO DE INFORMACIÓN, PÉRDIDA O MODIFICACIÓN DE CUALQUIER CONTENIDO DE SU EQUIPO.
            </p>

            <p className="text-justify">
              ASIMISMO, "INCRESCENDO FINTECH", NO SE HACE RESPONSABLE POR LAS FALLAS DE CONEXIÓN A INTERNET QUE EL "USUARIO Y/O CLIENTE" PRESENTE EN EL ACCESO O DURANTE SU SESIÓN EN LA "WALLET".
            </p>

            <h3 className="text-base sm:text-lg font-semibold text-foreground mt-6 mb-3">(H) CONTINUIDAD DEL SERVICIO</h3>

            <p className="text-justify">
              "INCRESCENDO FINTECH", RESPONDERÁ AL "USUARIO Y/O CLIENTE" POR LA ADECUADA PRESTACIÓN DE SUS SERVICIOS Y EL DEBIDO FUNCIONAMIENTO DE LA "WALLET", SALVO QUE SE PRESENTE LA OCURRENCIA DE ALGÚN CASO FORTUITO O DE FUERZA MAYOR, O SE GENEREN A CAUSA DE OTROS EQUIPOS Y SISTEMAS AUTOMATIZADOS FUERA DE SU CONTROL.
            </p>

            <p className="text-justify">
              EN CASO DE FALLAS O ERRORES EN LA OPERACIÓN DE LA "WALLET", "INCRESCENDO FINTECH", LO COMUNICARÁ AL "USUARIO Y/O CLIENTE" MEDIANTE UN MENSAJE GENERADO EN LA PROPIA "WALLET" Y CUANDO ESTA DURE MÁS DE 30 MINUTOS, MEDIANTE AVISO POR ESCRITO AL CORREO ELECTRÓNICO DEL "USUARIO Y/O CLIENTE".
            </p>

            <h3 className="text-base sm:text-lg font-semibold text-foreground mt-6 mb-3">(I) ALERTAS</h3>

            <p className="text-justify">
              INCRESCENDO FINTECH, COMUNICARÁ AL "USUARIO Y/O CLIENTE" A TRAVÉS DE LA "WALLET", Y AL CORREO ELECTRÓNICO QUE PROPORCIONE PARA RECIBIR NOTIFICACIONES CONFORME A LOS PRESENTES "TÉRMINOS Y CONDICIONES", DE CUALQUIER MOVIMIENTO, ACTUALIZACIONES DE SU INFORMACIÓN PERSONAL O DATOS DE CONTACTO, INICIOS DE SESIÓN EN DISPOSITIVOS INUSUALES Y CUALQUIER OTRA QUE INCRESCENDO FINTECH, CONSIDERE NECESARIA PARA QUE EL "USUARIO Y/O CLIENTE" PUEDA PREVENIR ACCESOS U OPERACIONES NO AUTORIZADOS.
            </p>

            <h3 className="text-base sm:text-lg font-semibold text-foreground mt-6 mb-3">(J) INFORMACIÓN SOBRE RIESGOS TECNOLÓGICOS, CIBERNÉTICOS Y DE FRAUDE</h3>

            <p className="text-justify">
              "INCRESCENDO FINTECH", PONDRÁ A DISPOSICIÓN DEL "USUARIO Y/O CLIENTE", DE MANERA GRATUITA, VÍA CORREO ELECTRÓNICO Y A TRAVÉS DE LA "WALLET", INFORMACIÓN PARA EVITAR POSIBLES RIESGOS TECNOLÓGICOS, CIBERNÉTICOS Y DE FRAUDE EN EL USO DE SUS SERVICIOS.
            </p>

            <p className="text-justify">
              AL ACEPTAR LOS "TÉRMINOS Y CONDICIONES", EL "USUARIO Y/O CLIENTE" PERSONA FÍSICA, MANIFIESTA QUE ACTÚA A NOMBRE Y CUENTA PROPIA, PARA LLEVAR A CABO LAS ACTIVIDADES Y SERVICIOS OFRECIDOS A TRAVÉS DE LA "WALLET".
            </p>

            <h3 className="text-base sm:text-lg font-semibold text-foreground mt-6 mb-3">(K) JURISDICCIÓN Y RESOLUCIÓN DE CONTROVERSIAS</h3>

            <p className="text-justify">
              "INCRESCENDO FINTECH" TENDRÁ LA FACULTAD DE ELEGIR RESOLVER CUALQUIER CONFLICTO, CONTROVERSIA O RECLAMACIÓN QUE SE SUSCITE O ESTÉ RELACIONADA CON LOS "TÉRMINOS Y CONDICIONES" O DEL SERVICIO PROPORCIONADO EN RELACIÓN CON LOS MISMOS, MEDIANTE UN PROCEDIMIENTO DE ARBITRAJE VINCULANTE CONFORME LAS REGLAS DEL CENTRO DE ARBITRAJE Y LAS DISPOSICIONES APLICABLES EN LA CIUDAD DE MÉXICO. TODA CONTROVERSIA O RECLAMACIÓN SERÁ ARBITRADA DE FORMA INDIVIDUAL. EL ARBITRAJE SE LLEVARÁ A CABO EN LA CIUDAD DE MÉXICO, LA SENTENCIA SOBRE EL LAUDO ARBITRAL PODRÁ SER PRESENTADA EN CUALQUIER TRIBUNAL QUE TENGA JURISDICCIÓN DEL MISMO.
            </p>

            <p className="text-justify">
              CUALQUIER ARBITRAJE SERÁ CONFIDENCIAL Y NI EL "USUARIO Y/O CLIENTE" NI "INCRESCENDO FINTECH" PUEDEN REVELAR LA EXISTENCIA, CONTENIDO O RESULTADOS DE CUALQUIER ARBITRAJE, EXCEPTO CUANDO LO REQUIERA LA LEY O LOS EFECTOS DE LA SENTENCIA ARBITRAL. TODOS LOS HONORARIOS Y GASTOS DE ARBITRAJE ADMINISTRATIVOS, Y DE CUALQUIER PROCEDIMIENTO DE CARÁCTER JUDICIAL SERÁN CUBIERTOS POR CADA UNA DE LAS PARTES QUE PARTICIPEN EN DICHO PROCEDIMIENTO. EL "USUARIO Y/O CLIENTE" ACEPTA SOMETERSE A LA JURISDICCIÓN DE LOS TRIBUNALES DE LA CIUDAD DE MÉXICO.
            </p>

            <h3 className="text-base sm:text-lg font-semibold text-foreground mt-6 mb-3">(L) VIGENCIA DE LOS "TÉRMINOS Y CONDICIONES"</h3>

            <p className="text-justify">
              LOS PRESENTES "TÉRMINOS Y CONDICIONES", SURTEN EFECTOS Y SON APLICABLES A PARTIR DE LAS CONTRATACIONES DE MEMBRESÍAS HECHAS POR EL "USUARIO Y/O CLIENTE" A PARTIR DEL 01 DE ABRIL DE 2026.
            </p>

            <p className="text-xs sm:text-sm text-muted-foreground mt-8">
              <strong>Fecha última actualización:</strong> Abril 01, 2026
            </p>
          </div>
        </div>
      </main>

      <PublicFooter />
    </div>
  );
};

export default TerminosCondiciones;